export enum ROUTES {
  WELCOME = 'Welcome',
  LOGIN_SCREEN = 'LoginScreen',
  SIGNUP_SCREEN = 'SignUpScreen',
  HOME_SCREEN = 'HomeScreen',
  SET_PROFILE_SCREEN = 'SetProfileScreen',
  SET_DRIVER_PROFILE_SCREEN = 'SetDriverProfileScreen',
  PHONE_VERIFICATION_SCREEN = 'PhoneVerificationScreen',
  DRIVER_TRIP = 'DriverTrip',
  PASSENGER_TRIP_GUIDE = 'PassengerTripGuide',
  NOTIFICATIONS_SCREEN = 'NotificationsScreen',
  MY_PROFILE_SCREEN = 'MyProfileScreen',
  TAB_SCREEN = 'TabScreen',
  HOME_TRIPS_STACK_SCREEN = 'HomeTripsStackScreen',
}
